Add html-minifier
egoist/unvue pull request #138
Opened 2019-04-11 13:40 UTC by SamGold05

2019-04-11 14:46 UTC, IlyaSemenov commented
Please make this optional and disabled by default. When enabled, I think it should accept the options object so that a user may enable/disable certain options (in particular, `removeComments: true` is not desired in some applications). `true` may mean everything enabled.

2019-04-11 14:51 UTC, IlyaSemenov requested changes

2019-04-11 14:51 UTC, IlyaSemenov commented on lib/index.js
> +const minifyHTML = require('./utils/minifyHTML')
Please make it `minifyHtml` not `minifyHTML` (that's a typical convention for abbreviations).

2019-04-11 14:51 UTC, IlyaSemenov commented on lib/utils/minifyHTML.js
> +  return minify(html, {
Why the redundant return? You're using ES6 syntax already.

```js
module.exports = html => minify(html, {
 ...
})
```

2019-04-11 14:51 UTC, IlyaSemenov commented on tap-snapshots/examples-custom-root-component-index.test.js-TAP.test.js
> +<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=n
Please keep the existing tests unchanged. They are now unreadable without purpose.

Please add a **new** test instead which tests the new behaviour (or better two, one with default options and one with custom minify options).

2019-04-11 16:22 UTC, egoist commented
Not sure if this is safe to do, it might break [Client Side Hydration](https://ssr.vuejs.org/guide/hydration.html)

2019-04-13 05:52 UTC, IlyaSemenov commented
The tests now fail on Linux because you forgot to change the module file name casing.

Otherwise looks good to me.

2019-04-14 16:46 UTC, SamGold05 commented
Sorry, vscode doesn't recognize renaming when change case of filename.

2019-04-14 16:47 UTC, SamGold05 commented
Now it will be ok.

2019-04-16 08:34 UTC, IlyaSemenov approved these changes

2019-05-10 13:05 UTC, closed without merging

2019-05-10 13:11 UTC, IlyaSemenov commented
:tada: This issue has been resolved in version 4.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ream)
- [GitHub release](https://github.com/ream/ream/releases/tag/v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2019-05-10 13:15 UTC, IlyaSemenov commented
I published this with a few changes. From the user point of view, I renamed the option to `minifyHtml` (which goes in better accordance with `minimize`).

In the code, I first uniformed the HTML rendering so that minifyHtml could be applied in one place instead of copy/pasting the logic.